name: plugger
description: A Flutter package which helps to encapsulate app configurations.
repository: https://github.com/harkairt/plugger
version: 0.0.1

environment:
  sdk: ">=3.0.5 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
